### PR TITLE
Bump a year on copyright

### PR DESCRIPTION
**Pull request by janczer**

### CODE REVIEW

**Comment by 0crat** [comment]
@yegor256 please, pay attention to this pull request

**Comment by 0crat** [comment]
Job `gh:yegor256/xembly#77` is now in scope.

**Comment by yegor256** [comment]
@rultor merge

**Comment by janczer** [comment]
@yegor256 This pull request change only comments. Why it's failed?

**Comment by yegor256** [comment]
@janczer see http://www.yegor256.com/2015/01/15/how-to-cut-corners.html

**Comment by 0crat** [comment]
The job [#77](https://github.com/yegor256/xembly/issues/77) is now out of scope

**Pull request closed without merging**
