### PR TITLE
Can parse with new lines and spaces after last command

### PR DESCRIPTION
**Pull request by maxonfjvipon**
[This PR](https://github.com/objectionary/eo/pull/2767) is failed because Xembly is unable to parse directives with spaces and new lines after last command. Fixed it

### CODE REVIEW

**Comment by maxonfjvipon** [comment]
@yegor256 please have a look

**Comment by maxonfjvipon** [comment]
@yegor256 please have a look

**Comment by yegor256** [comment]
@rultor merge

**Comment by yegor256** [comment]
@rultor release, tag is `0.31.1`

**Comment by yegor256** [comment]
@maxonfjvipon thanks!

**Pull request merged**
