### PR TITLE
#49 - updated pom

### PR DESCRIPTION
**Pull request by maurezen**

### CODE REVIEW

**Comment by davvd** [comment]
Thanks, let me find someone who can review this pull request

**Comment by davvd** [comment]
@krzyk please review, thanks

**Comment by krzyk** [comment]
@rultor merge pls

**Comment by yegor256** [comment]
@rultor merge

**Comment by davvd** [comment]
@krzyk thank you, added **15 mins** to your acc, payment num is `51287988`... +15 added to your rating, current score is: [+3619](http://www.netbout.com/b/35035?open=rating)

**Comment by davvd** [comment]
@rultor deploy now pls

**Pull request merged**
