### PR TITLE
feat(#64): Omit XML Header in Xembler Output

### PR DESCRIPTION
**Pull request by volodya-lombrozo**
Omit the following XML header in Xembler output:
```xml
<?xml version="1.0" encoding="UTF-8"?>
```

To do so, we now can use the following:
```java
new Xembler(directives, new Output.Node()).xml();
```

Closes: #64.

### CODE REVIEW

**Comment by volodya-lombrozo** [comment]
@yegor256 Could you take a look, please? I need that feature in other project.

**Comment by volodya-lombrozo** [comment]
@yegor256 Could you take a look one more time, please?

**Comment by yegor256** [comment]
@rultor merge

**Comment by volodya-lombrozo** [comment]
@yegor256 Could you release a new version, please?

**Comment by yegor256** [comment]
@rultor release, tag is `0.29.0`

**Pull request merged**
