### PR TITLE
Update appveyor.yml

### LINKED ISSUE #88: Windows builds fail with Maven >=3.3.1
```
[INFO] --- maven-invoker-plugin:1.9:run (default) @ xembly ---
[INFO] Building: saxon\pom.xml
[INFO] ..FAILED (0.0 s)
[INFO]   Maven invocation failed. Error configuring command-line. Reason: Maven executable not found at: C:\dev-tools\apache-maven-3.5.2\bin\mvn.bat
[INFO] Building: xerces\pom.xml
[INFO] ..FAILED (0.0 s)
[INFO]   Maven invocation failed. Error configuring command-line. Reason: Maven executable not found at: C:\dev-tools\apache-maven-3.5.2\bin\mvn.bat
[INFO] -------------------------------------------------
[INFO] Build Summary:
[INFO]   Passed: 0, Failed: 2, Errors: 0, Skipped: 0
[INFO] -------------------------------------------------
[ERROR] The following builds failed:
[ERROR] *  saxon\pom.xml
[ERROR] *  xerces\pom.xml
[INFO] -------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 30.964 s
[INFO] Finished at: 2018-08-10T15:38:41+08:00
[INFO] Final Memory: 47M/719M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-invoker-plugin:1.9:run (default) on project xembly: 2 builds failed. See console output above for details. -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
```

In Maven 3.3.1, the Maven executable for windows was changed from `mvn.bat` to `mvn.cmd`, so Invoker now fails.

Xembly currently inherits `maven-invoker-plugin:1.9` from `com.jcabi:parent`. The issue is fixed in [version 1.10](https://blog.soebes.de/blog/2015/04/03/apache-maven-invoker-plugin-version-1-dot-10-released/), so upgrading will probably fix this. However, the project is about two years or so behind in terms of library updates, so be mindful that jumping straight into the latest `parent` will probably break a lot of things,

### PR DESCRIPTION
**Pull request by xaircore**
Close #88

Many thanks for your contribution, we truly appreciate it. We will appreciate it even more, if you make sure that you can say "YES" to each point in this short checklist:

  - You made a small amount of changes (less than 100 lines, less than 10 files)
  - You made changes related to only one bug (create separate PRs for separate problems)
  - You are ready to defend your changes (there will be a code review)
  - You don't touch what you don't understand
  - You ran the build locally and it passed

This article will help you understand what we are looking for: http://www.yegor256.com/2015/02/09/serious-code-reviewer.html

Thank you for your contribution!

### CODE REVIEW

**Comment by 0crat** [comment]
@carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda) please, pay attention to this pull request

**Comment by 0crat** [comment]
@xaircore[/z](https://www.0crat.com/u/xaircore) this pull request is too small, just 3 lines changed (less than 10), there will be no formal code review, see [§53](http://www.zerocracy.com/policy.html#53) and [§28](http://www.zerocracy.com/policy.html#28); in the future, try to make sure your pull requests are not too small; @carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda) please review this and merge or reject

**Comment by carlosmiranda** [comment]
@xaircore thanks, but this does not look related to #88.

**Comment by 0crat** [comment]
Job `gh:yegor256/xembly#94` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope

**Pull request closed without merging**
