### PR TITLE
update License date from 2017 to 2019

### PR DESCRIPTION
**Pull request by gouzal**
Update License from 2017 to 2019 in all files.

### CODE REVIEW

**Comment by 0crat** [comment]
@carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda) please, pay attention to this pull request

**Comment by 0crat** [comment]
Job [#92](https://github.com/yegor256/xembly/issues/92) is now in scope, role is `REV`

**Comment by 0crat** [comment]
@carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda) everybody who has role `REV` is banned at [#92](https://github.com/yegor256/xembly/issues/92); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by carlosmiranda** [comment]
@rultor merge

**Comment by 0crat** [comment]
Job `gh:yegor256/xembly#92` is not assigned, can't get performer

**Comment by 0crat** [comment]
The job [#92](https://github.com/yegor256/xembly/issues/92) is now out of scope

**Comment by 0crat** [comment]
Payment to `ARC` for a closed pull request, as in [§28](http://www.zerocracy.com/policy.html#28): +10 point(s) just awarded to @carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda)

**Pull request merged**
