### PR TITLE
#46 - fixed copyright section

### PR DESCRIPTION
**Pull request by RomanKisilenko**
Please review this PR.

### CODE REVIEW

**Comment by davvd** [comment]
Thanks, I'll ask someone to do a code review here, thanks for your pull request

**Comment by davvd** [comment]
@carlosmiranda review this one, please

**Comment by carlosmiranda** [comment]
@RomanKisilenko Thanks, I don't have any comments.

**Comment by carlosmiranda** [comment]
@rultor Let's merge please.

**Comment by carlosmiranda** [comment]
@yegor256 May we be added to `.rultor.yml`?

**Comment by yegor256** [comment]
@rultor merge it

**Comment by davvd** [comment]
@carlosmiranda thanks, I just added **16 mins** to your account, payment `50570354`... added +16 to your rating, now it is equal to [+1714](http://www.netbout.com/b/35023?open=rating)

**Comment by davvd** [comment]
@rultor deploy now pls

**Pull request merged**
