### PR TITLE
Coverage by codecov

### LINKED ISSUE #87: Migrate to Codecov
We were previously using [Coveralls](http://coveralls.io/) for our code coverage reporting. This was removed recently (see https://github.com/yegor256/xembly/commit/1a945e4f4b32e028134ba90c317cfb331858adbc).

Let's migrate the project to [Codecov](https://codecov.io/), which is the preferred service for our newer projects.

### PR DESCRIPTION
**Pull request by xaircore**
Support code coverage by codecov. Close #87

### CODE REVIEW

**Comment by 0crat** [comment]
@carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda) please, pay attention to this pull request

**Comment by 0crat** [comment]
Job [#90](https://github.com/yegor256/xembly/issues/90) is now in scope, role is `REV`

**Comment by 0crat** [comment]
@carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda) everybody who has role `REV` is banned at [#90](https://github.com/yegor256/xembly/issues/90); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by xaircore** [comment]
assign @yegor256

**Comment by carlosmiranda** [comment]
@xaircore sorry, I have to reject this. We cannot report code coverage on the main project using code from your fork.

**Comment by 0crat** [comment]
Job `gh:yegor256/xembly#90` is not assigned, can't get performer

**Comment by 0crat** [comment]
The job [#90](https://github.com/yegor256/xembly/issues/90) is now out of scope

**Comment by 0crat** [comment]
Pull request [#90](https://github.com/yegor256/xembly/issues/90) was not merged, no payment for `ARC`, see [§28](http://www.zerocracy.com/policy.html#28)

**Comment by xaircore** [comment]
@carlosmiranda Sorry, it's my bad. You right. Badget must link to this repository but not my. If i revert my changes from markdown, can we merge my PL?

**Pull request closed without merging**
